import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--A', type=int, default=5, help='')
parser.add_argument('--log_path', type=str, default='/root/autodl-tmp/Derain/logs', help='')
parser.add_argument('--lr', type=float, default=1e-3, help='')
parser.add_argument('--lr_min', type=float, default=1e-6, help='')
parser.add_argument('--train_path', type=str, default='/root/autodl-tmp/Derain/Dataset/Train/', help='')
parser.add_argument('--val_path', type=str, default='/root/autodl-tmp/Derain/Dataset/Val/', help='')
parser.add_argument('--num_heads', type=int, default=8, help='')
parser.add_argument('--epoch', type=int, default=100)
parser.add_argument('--channel', type=int, default=32)
parser.add_argument('--val_after_every', type=int, default=2)
parser.add_argument('--win_size', type=int, default=64)
parser.add_argument('--stride', type=int, default=[64, 64], help='Stride for moving the cropping window')
parser.add_argument('--preprocess', type=bool, default=True)
parser.add_argument('--batch_size', type=int, default=1)
parser.add_argument('--Resume', type=bool, default=False)

args = parser.parse_args()